version: '3'
services:
  dice:
    build: .
    ports:
      - "8080:8080"
    environment:
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: https://{TENANTGOESHERE}.collect.observeinc.com/v1/otel/v1/traces
      OTEL_EXPORTER_OTLP_HEADERS: Authorization=Bearer {TOKENGOESHERE}
      OTEL_NODE_RESOURCE_DETECTORS: env,host
      OTEL_SERVICE_NAME: example-node
      NODE_OPTIONS: --require @opentelemetry/auto-instrumentations-node/register
